version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/build-push"
      - "/.github/actions/create-pr"
      - "/create-release"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling: "
