name: PR tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      config: ${{ steps.filter.outputs.config }}
      milestone: ${{ steps.filter.outputs.milestone }}
      labels: ${{ steps.filter.outputs.labels }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            config:
              - "pkg/config/config.yaml"
            milestone:
              - "cmd/milestones/**"
            labels:
              - "cmd/labels/**"

  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: Swatinem/rust-cache@v2
      - name: Crate Format
        run: cargo fmt --check
      - name: Crate Check
        run: cargo check
      - name: Crate Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview
      - name: Crate Test with coverage
        run: cargo llvm-cov --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          flags: unit-tests
          files: codecov.json
          slug: guacsec/trustify-release-tools

  check-milestones:
    needs: build
    if: ${{ needs.build.outputs.config == 'true' || needs.build.outputs.milestone == 'true' }}
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: RUST_LOG=info cargo run --bin milestones -- --config pkg/config/config.yaml

  check-labels:
    needs: build
    if: ${{ needs.build.outputs.config == 'true' || needs.build.outputs.milestone == 'true' }}
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: RUST_LOG=info cargo run --bin labels -- --config pkg/config/config.yaml
