name: PR Closed

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  backport_job:
    permissions:
      pull-requests: write
      contents: write
      actions: write
    if: github.event.pull_request.merged == true
    secrets: inherit
    uses: ./.github/workflows/backport.yaml
